### ISSUE TITLE
curious icon tic on stop icons

### ISSUE THREAD

**Issue by alanb2718** [OneBusAway/onebusaway-ios#644] opened 2023-02-21 19:05 UTC
I am seeing a peculiar tic on the stop icons on the OneBusAway map.  The vehicle in the stop icon will very briefly swell or the direction arrow will flash in the wrong direction.  See attached video.  This is version 23.1.0 on an iPhone 12 mini, iOS 16.1.2.

https://user-images.githubusercontent.com/918773/220435878-6a4e7730-35ca-4fe9-bebf-5968099f56ee.mov

**Comment by ualch9** [comment] 2023-02-21 19:21
Duplicate of #563

**Closed by ualch9** 2023-02-21 19:21 UTC
Labels: Bug, Ux
