### ISSUE TITLE
Map accessibility bug

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#555] opened 2021-10-13 18:43 UTC
Feedback from Marci C:

> I just opened One Bus Away this morning and found a bug on the map page. In the past, when I would swipe around the page, voiceover would announce the name of the stop the cursor landed on. That is no longer the case. Now all it says when I land on a stop icon is “shows more info“ it does not say the name of the stop at all. I often use the map page as my starting place because I travel to so many different places and don’t have all of them bookmarked. Can you please check this and get back to me about a solution?

I don't know what version of OBA Marci is using here, unfortunately, so I am not clear if this might be already fixed.

**Comment by ualch9** [comment] 2021-10-13 18:56
"shows more info" is what voiceover says after the stop name, so voiceover is properly focused on stop annotations, but i guess the stop name isn't getting populated into the accessibilityLabel? please follow up and get the version number and maybe an example stop if possible.

**Comment by cathy810218** [comment] 2021-11-11 22:21
Hi Aaron & Alan!
I was just using the accessibility thing in OBA today and thought I should add some info here.
I think from what I am seeing (in the video attached), it's working properly.
(Version 21.6 latest on the app store)
https://user-images.githubusercontent.com/12047881/141376939-c939b90f-3037-4049-b6bc-b9f8e1dff30c.mp4

**Comment by ualch9** [comment] 2021-11-12 02:52
thanks, cathy! if i'm understanding correctly, this problem no longer exists. since the user report can't be reproduced, im gonna close this issue.

**Closed by ualch9** 2021-11-12 02:52 UTC
Labels: Map, Accessibility, Bug
