### ISSUE TITLE
Stop 75020 in San Diego is crashing the app

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/onebusaway-ios#531] opened 2021-09-22 18:46 UTC
Repro:

1. Change region to San Diego
2. Search for stop number 75020 (Should be "Santee Town Center Station")
3. Open it.

Expected: I see stop information.

Actual: The app crashes.

```
2021-09-24 10:52:38.916263-0700 App[14054:355079] Enqueuing URL: https://realtime.sdmts.com/api/api/where/arrivals-and-departures-for-stop/MTS_75020.json?minutesBefore=5&minutesAfter=35&version=2&key=org.onebusaway.iphone&app_uid=46F366AF-F172-4EE1-875B-4F9CC8CB116C&app_ver=21.4.2
2021-09-24 10:52:41.744796-0700 App[14054:354743] *** Assertion failure in -[NSDiffableDataSourceSectionSnapshot appendItems:], NSDiffableDataSourceSectionSnapshot.m:56
2021-09-24 10:52:41.749611-0700 App[14054:354743] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Supplied identifiers are not unique.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010fc95bb4 __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x000000010f3b0be7 objc_exception_throw + 48
	2   Foundation                          0x0000000111a41c12 _userInfoForFileAndLine + 0
	3   UIKitCore                           0x00000001206cfbe6 -[NSDiffableDataSourceSectionSnapshot appendItems:] + 546
	4   libswiftUIKit.dylib                 0x0000000113c8eb5b $s5UIKit35NSDiffableDataSourceSectionSnapshotV6append_2toySayxG_xSgtF + 251
	5   OBAKit                              0x0000000112b85a0e $s6OBAKit11OBAListViewC9applyData8animatedySb_tF + 4158
	6   OBAKit                              0x0000000112c4c494 $s6OBAKit18StopViewControllerC13dataDidReload33_CA09024D532488274D9EB8196D783792LLyyF + 84
	7   OBAKit                              0x0000000112c3d44f $s6OBAKit18StopViewControllerC12stopArrivals0A4Core0bF0CSgvW + 239
	8   OBAKit                              0x0000000112c3d571 $s6OBAKit18StopViewControllerC12stopArrivals0A4Core0bF0CSgvs + 129
	9   OBAKit                              0x0000000112c44f9e $s6OBAKit18StopViewControllerC10updateDatayyFys6ResultOy0A4Core15RESTAPIResponseCyAG0B8ArrivalsCGs5Error_pGcfU_ + 1342
	10  OBAKit                              0x0000000112a92039 $ss6ResultOy10OBAKitCore15RESTAPIResponseCyAC12StopArrivalsCGs5Error_pGIegg_AJIegn_TR + 25
	11  OBAKitCore                          0x0000000110b01903 $s10OBAKitCore18DecodableOperationC23invokeCompletionHandler33_E953A8D394A640E6985A5F94E5107756LLyyFyycfU_ + 963
	12  OBAKitCore                          0x0000000110aac138 $sIeg_IeyB_TR + 40
	13  libdispatch.dylib                   0x0000000113e7ea28 _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x0000000113e7fc0c _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x0000000113e8e376 _dispatch_main_queue_callback_4CF + 1195
	16  CoreFoundation                      0x000000010fc0385d __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	17  CoreFoundation                      0x000000010fbfe0ba __CFRunLoopRun + 2772
	18  CoreFoundation                      0x000000010fbfd103 CFRunLoopRunSpecific + 567
	19  GraphicsServices                    0x0000000114a0ccd3 GSEventRunModal + 139
	20  UIKitCore                           0x0000000120735e63 -[UIApplication _run] + 928
	21  UIKitCore                           0x000000012073aa53 UIApplicationMain + 101
	22  App                                 0x000000010e651f0f main + 495
	23  dyld                                0x000000010ec06e1e start_sim + 10
	24  ???                                 0x0000000000000001 0x0 + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
```

**Comment by ualch9** [comment] 2021-09-25 02:15
this is an `OBAListView` problem. do you want me to take a look, @aaronbrethorst?

**Comment by aaronbrethorst** [comment] 2021-09-25 03:23
I would be delighted if you could! Thank you!

**Comment by ualch9** [comment] 2021-09-27 19:11
Can't reproduce when built against iOS 15. @aaronbrethorst is the crash log from Xcode 12 or 13?

**Comment by aaronbrethorst** [comment] 2021-09-27 20:19
@ualch9 - @devinbraun updated SDMTS's GTFS file to remove the offending duplicate in this case.

**Comment by ualch9** [comment] 2021-09-27 23:45
ok, closing this then. i'll open a different issue for gracefully handling dupes.

**Closed by ualch9** 2021-09-27 23:45 UTC
Labels: Stops, Bug

**Comment by ualch9** [comment] 2021-10-01 21:12
continued in #538.
