### ISSUE TITLE
Duplicate buses

### ISSUE THREAD

**Issue by captainjack63** [OneBusAway/onebusaway-ios#513] opened 2021-09-05 20:20 UTC
I figured that over a year this bug 🐛 would have been reported and solved. So there are many duplicate buses 🚌 in this app. Here is one example. 

![009FEBE0-04D8-446D-80A8-61F58F486F91](https://user-images.githubusercontent.com/39658481/132140339-a3ae1466-3ce8-422a-b73d-9d20b75105c9.png)

**Comment by ualch9** [comment] 2021-09-08 21:17
@barbeau 

Here is a gist for the JSON response for this stop: https://gist.github.com/ualch9/9519b1967db0da6c99aa5e8a61e62d15

Attached below is a screenshot of the problem reproduced.
![Simulator Screen Shot - iPhone 12 Pro - 2021-09-08 at 14 15 47](https://user-images.githubusercontent.com/22162410/132586754-e93f4e70-51f4-4902-8421-7f232f0f857a.png)

**Comment by barbeau** [comment] 2021-09-08 21:32
Hmmm, I see the same on Android. But only some arrivals are duplicated. I'm guessing it's a real-time data issue where they are accidently assigning two vehicles to the same trip - that's what the JSON data seems to indicate (`"vehicleId": "29_MCOB-DO:123:0:Weekday:1:21MAR:41063:12345"` and `"vehicleId": "29_15107"` are both assigned to `"tripId": "29_9140712__MCOB-DO:123:0:Weekday:1:21MAR:41063:12345"`). I want to say that this is already a known issue at Community Transit and isn't easily solvable because it's part of their real-time info generation system, but let me ping @sheldonabrown and see what he says.

![image](https://user-images.githubusercontent.com/928045/132587671-ff88adfa-e7f9-4eb4-85ba-8e5ff4279e72.png)

**Comment by ualch9** [comment] 2021-10-04 18:51
@barbeau any updates on this?

**Comment by barbeau** [comment] 2021-10-04 19:06
Last I heard Sound Transit/CS was testing a fix but hadn't scheduled a release yet. Let me ping Sheldon again.

**Comment by ualch9** [comment] 2021-10-04 19:07
ok, since this is unrelated to iOS, i'm going to close this issue.

**Closed by ualch9** 2021-10-04 19:07 UTC
